// Mocks generated by Mockito
// Do not modify this file by hand

import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;
import 'package:nilecare_flutter/core/api/api_client.dart' as _i3;

class MockFlutterSecureStorage extends _i2.Mock
    implements _i1.FlutterSecureStorage {}

class MockApiClient extends _i2.Mock implements _i3.ApiClient {}
