// Mocks generated by Mockito
// Do not modify this file by hand

import 'package:dio/dio.dart' as _i1;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i3;

class MockDio extends _i3.Mock implements _i1.Dio {}

class MockFlutterSecureStorage extends _i3.Mock
    implements _i2.FlutterSecureStorage {}
