name: flutter_plant
description: A new Flutter project.

# Prevents accidental publishing to pub.dev.
publish_to: none # Remove this line if you wish to publish to pub.dev

# Version of your application.
# Version format: x.y.z+build_number
version: 1.0.0+1

# Dart SDK constraints.
environment:
  sdk: ">=3.4.4 <4.0.0"

# Dependencies required for your project.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_bottom_navigation_bar: ^1.3.3
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific settings.
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/animated.jpg
    - lib/assets/images/background.jpg
    - lib/assets/images/beautiful.jpg
    - lib/assets/images/download.jpg
    - lib/assets/images/forgotPassword.jpg
    - lib/assets/images/forgotPassword2.jpg
    - lib/assets/images/garden.jpg
    - lib/assets/images/green.jpg
    - lib/assets/images/indoor.jpg
    - lib/assets/images/outdoor.jpg
    - lib/assets/images/plant.jpg
    - lib/assets/images/plant3.jpg
    - lib/assets/images/profile.jpg
    - lib/assets/images/profile2.jpg
    - lib/assets/images/reset-password.avif
    - lib/assets/images/reset.png
    - lib/assets/images/signin.jpg
    - lib/assets/images/signin2.jpg
    - lib/assets/images/signUp.jpg
    - lib/assets/images/signUp2.jpg


# Optional: Custom fonts can be added here.
# fonts:
#   - family: CustomFont
#     fonts:
#       - asset: fonts/CustomFont-Regular.ttf
#       - asset: fonts/CustomFont-Bold.ttf
#         weight: 700
