// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJVUqAFJ_4aaQ2JMmkPO3LZ7_2_Rue1Pc',
    appId: '1:878516400319:web:5656b0b49b11657b17d60a',
    messagingSenderId: '878516400319',
    projectId: 'loginapp-2db13',
    authDomain: 'loginapp-2db13.firebaseapp.com',
    storageBucket: 'loginapp-2db13.appspot.com',
    measurementId: 'G-QPR753G9Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWBu9aFkwHYonTLUu7rdPvXTj-XozdhqQ',
    appId: '1:878516400319:android:9854488c32f1324617d60a',
    messagingSenderId: '878516400319',
    projectId: 'loginapp-2db13',
    storageBucket: 'loginapp-2db13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsETf73ye0hHR5p0odKIq8bWL8MtS4oAo',
    appId: '1:878516400319:ios:00476d5330bdaa2117d60a',
    messagingSenderId: '878516400319',
    projectId: 'loginapp-2db13',
    storageBucket: 'loginapp-2db13.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsETf73ye0hHR5p0odKIq8bWL8MtS4oAo',
    appId: '1:878516400319:ios:00476d5330bdaa2117d60a',
    messagingSenderId: '878516400319',
    projectId: 'loginapp-2db13',
    storageBucket: 'loginapp-2db13.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJVUqAFJ_4aaQ2JMmkPO3LZ7_2_Rue1Pc',
    appId: '1:878516400319:web:d49336b19d9153b617d60a',
    messagingSenderId: '878516400319',
    projectId: 'loginapp-2db13',
    authDomain: 'loginapp-2db13.firebaseapp.com',
    storageBucket: 'loginapp-2db13.appspot.com',
    measurementId: 'G-Z1V7BXKZWE',
  );
}
