class Plant {
  final int plantId;
  final int price;
  final String size;
  final double rating;
  final int humidity;
  final String temperature;
  final String category;
  final String plantName;
  final String imageURL;
  final String description;
  final bool isFavorated;

  Plant({
    required this.plantId,
    required this.price,
    required this.size,
    required this.rating,
    required this.humidity,
    required this.temperature,
    required this.category,
    required this.plantName,
    required this.imageURL,
    required this.description,
    this.isFavorated = false, // Default value
  });

  static List<Plant> plantList = [
    Plant(
      plantId: 0,
      price: 22,
      category: 'Indoor',
      plantName: 'Sanseyiera',
      size: 'Small',
      rating: 4.5,
      humidity: 34,
      temperature: '23 - 34',
      imageURL: 'assets/images/indoor.jpg',
      description: 'This plant is one of the best plants. It grows in most of the regions in the world, even in the harshest weather conditions.',
      isFavorated: true,
    ),
    Plant(
      plantId: 1,
      price: 32,
      category: 'Outdoor',
      plantName: 'Sanserif',
      size: 'Big',
      rating: 6.5,
      humidity: 27,
      temperature: '23 - 34',
      imageURL: 'assets/images/outdoor.jpg',
      description: 'This plant is one of the best plants. It grows in most of the regions in the world, even in the harshest weather conditions.',
      isFavorated: true,
    ),
    Plant(
      plantId: 2,
      price: 41,
      category: 'garden',
      plantName: 'Heymen',
      size: 'Small',
      rating: 6.0,
      humidity: 44,
      temperature: '33 - 42',
      imageURL: 'assets/images/garden.jpg',
      isFavorated: false,
      description: 'This plant is one of the best plants. It grows in most of the regions in the world, even in the harshest weather conditions.',
    ),
    Plant(
      plantId: 2,
      price: 41,
      category: 'green',
      plantName: 'Heymen',
      size: 'Small',
      rating: 6.0,
      humidity: 44,
      temperature: '33 - 42',
      imageURL: 'assets/images/green.jpg',
      isFavorated: false,
      description: 'This plant is one of the best plants. It grows in most of the regions in the world, even in the harshest weather conditions.',
    ),
    Plant(
      plantId: 2,
      price: 41,
      category: 'animated',
      plantName: 'Heymen',
      size: 'Small',
      rating: 6.0,
      humidity: 44,
      temperature: '33 - 42',
      imageURL: 'assets/images/animated.jpg',
      isFavorated: false,
      description: 'This plant is one of the best plants. It grows in most of the regions in the world, even in the harshest weather conditions.',
    ),
    Plant(
      plantId: 2,
      price: 41,
      category: 'plant',
      plantName: 'Heymen',
      size: 'Small',
      rating: 6.0,
      humidity: 44,
      temperature: '33 - 42',
      imageURL: 'assets/images/plant.jpg',
      isFavorated: false,
      description: 'This plant is one of the best plants. It grows in most of the regions in the world, even in the harshest weather conditions.',
    ),
    Plant(
      plantId: 2,
      price: 41,
      category: 'beautiful',
      plantName: 'Heymen',
      size: 'Small',
      rating: 6.0,
      humidity: 44,
      temperature: '33 - 42',
      imageURL: 'assets/images/download.jpg',
      isFavorated: false,
      description: 'This plant is one of the best plants. It grows in most of the regions in the world, even in the harshest weather conditions.',
    ),
    Plant(
      plantId: 2,
      price: 41,
      category: 'Indoor',
      plantName: 'Heymen',
      size: 'Small',
      rating: 6.0,
      humidity: 44,
      temperature: '33 - 42',
      imageURL: 'assets/images/garden.jpg',
      isFavorated: false,
      description: 'This plant is one of the best plants. It grows in most of the regions in the world, even in the harshest weather conditions.',
    ),
    Plant(
      plantId: 2,
      price: 41,
      category: 'Indoor',
      plantName: 'Heymen',
      size: 'Small',
      rating: 6.0,
      humidity: 44,
      temperature: '33 - 42',
      imageURL: 'assets/images/green.jpg',
      isFavorated: false,
      description: 'This plant is one of the best plants. It grows in most of the regions in the world, even in the harshest weather conditions.',
    ),
    Plant(
      plantId: 2,
      price: 41,
      category: 'Indoor',
      plantName: 'Heymen',
      size: 'Small',
      rating: 6.0,
      humidity: 44,
      temperature: '33 - 42',
      imageURL: 'assets/images/beautiful.jpg',
      isFavorated: false,
      description: 'This plant is one of the best plants. It grows in most of the regions in the world, even in the harshest weather conditions.',
    ),
    Plant(
      plantId: 2,
      price: 41,
      category: 'Indoor',
      plantName: 'Heymen',
      size: 'Small',
      rating: 6.0,
      humidity: 44,
      temperature: '33 - 42',
      imageURL: 'assets/images/background.jpg',
      isFavorated: false,
      description: 'This plant is one of the best plants. It grows in most of the regions in the world, even in the harshest weather conditions.',
    ),
    Plant(
      plantId: 2,
      price: 41,
      category: 'Indoor',
      plantName: 'Heymen',
      size: 'Small',
      rating: 6.0,
      humidity: 44,
      temperature: '33 - 42',
      imageURL: 'assets/images/animated.jpg',
      isFavorated: false,
      description: 'This plant is one of the best plants. It grows in most of the regions in the world, even in the harshest weather conditions.',
    ),
  ];
}
