// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxXQqVliNTSL7Y3nX_huQKgeqma1QyNt8',
    appId: '1:461221139586:web:016482125ff917d022509b',
    messagingSenderId: '461221139586',
    projectId: 'ecommerceapp-12d79',
    authDomain: 'ecommerceapp-12d79.firebaseapp.com',
    storageBucket: 'ecommerceapp-12d79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8H3ll8E_TAuietrSnYCMFiUXuudfbN4k',
    appId: '1:461221139586:android:52db830e1cb4f7a322509b',
    messagingSenderId: '461221139586',
    projectId: 'ecommerceapp-12d79',
    storageBucket: 'ecommerceapp-12d79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXat0VB_ztDytWkR-hPMTcin8_X1_LPto',
    appId: '1:461221139586:ios:c2ef466745e08a0622509b',
    messagingSenderId: '461221139586',
    projectId: 'ecommerceapp-12d79',
    storageBucket: 'ecommerceapp-12d79.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
